apiVersion: v1
kind: Service
metadata:
    name: "petestaks-5aa1"
    labels:
        app: "petestaks-5aa1"
spec:
    type: LoadBalancer
    ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: http
    selector:
        app: "petestaks-5aa1"